### ISSUE TITLE
Download Earlier Version of chromium

### ISSUE THREAD

**Issue by jbelmont** [dtolstyi/node-chromium#1]
Hello Dmytro,

First off thanks for this yarn package, it is great. I have a question, how can I download chromium for linux x64 architecture and specifically version 62? What would be the proper url for it?

Sincerely,

Jean-Marcel Belmont

**Comment by jbelmont** [comment]
Just a little bit of background on what I am trying to do. At my current company we are trying to use headless chromium with testem.js and we are running into issues with the gpu with the latest chromium. Not sure if you have used testem before but it is a test runner for ember.js

```javascript
/* eslint-env node */
const MultiReporter = require('testem-multi-reporter');
const TimeReporter = require('testem-time-reporter');
const XunitReporter = require('testem/lib/reporters/xunit_reporter');
const chromium = require('chromium');
const fs = require('fs');
const util = require('util');

const XUNIT_DEST = process.env.XUNIT_DEST || 'tests/xunit.xml';
const writeStream = fs.createWriteStream(XUNIT_DEST);

const reporters = [{
    ReporterClass: TimeReporter,
    args: [{ out: process.stdout }]
}, {
    ReporterClass: XunitReporter,
    args: [false, writeStream, { get: () => false }]
}];
const multiReporter = new MultiReporter({ reporters });

module.exports = {
    test_page: ['tests/index.html?filter=Acceptance%20|','tests/index.html?filter=!Acceptance%20|'],
    browser_start_timeout: 60,
    disable_watching: true,
    launchers: {
        chromium: {
            exe: chromium.path,
            args: [
                '--headless',
                '--disable-gpu',
                '--no-sandbox',
                '--disable-gesture-requirement-for-media-playback',
                '--allow-file-access',
                '--use-fake-device-for-media-stream',
                '--use-fake-ui-for-media-stream',
                '--remote-debugging-port=9222',
                '--remote-debugging-address=0.0.0.0',
                '--screen-size=1200x800',
                '--unsafely-treat-insecure-origin-as-secure',
                '--unsafely-allow-protected-media-identifier-for-domain',
                '--disable-web-security',
                '--test-type=browser',
                util.format('--user-data-dir=/tmp/chrome%s', Math.floor(Math.random() * 100))
            ],
            protocol: 'browser'
        }
    },

    launch_in_ci: [
        'chromium'
    ],
    launch_in_dev: [
        'chromium'
    ],
    browser_args: {
        chromium: [
            '--headless',
            '--disable-gpu',
            '--no-sandbox',
            '--disable-gesture-requirement-for-media-playback',
            '--allow-file-access',
            '--use-fake-device-for-media-stream',
            '--use-fake-ui-for-media-stream',
            '--remote-debugging-port=9222',
            '--remote-debugging-address=0.0.0.0',
            '--screen-size=1200x800',
            '--unsafely-treat-insecure-origin-as-secure',
            '--unsafely-allow-protected-media-identifier-for-domain',
            '--disable-web-security',
            '--test-type=browser',
            util.format('--user-data-dir=/tmp/chrome%s', Math.floor(Math.random() * 100))
        ]
    },
    reporter: multiReporter
};
```

Anyways I am thinking if we can get an earlier version of chromium then we can get away from this chromium error: **ERROR:gpu_process_transport_factory.cc(1043)] Lost UI shared context.**

**Comment by dtolstyi** [comment]
Hi, Jean-Marcel,

Thank you for your message. I will try to help you with your problem.
As far as I know, there are no separate prebuilt packages for linux x32 and
x64 architectures.
In addition, latest build in "Linux" snapshots dates to 2016.
As far as I understood, from now all Linux packages are stored in
*Linux_ChromiumOS_FullLinux_ChromiumOS_Full* (
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_ChromiumOS_Full/
)

First, I would recommend you to try to run the latest build of **Chromium**
from the folder I've mentioned before. For the moment of writing, here's
the link to the latest version:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_ChromiumOS_Full/526333/

If this doesn't work for you, the easiest way to get version 62 is to build
it yourself. You can find sources of the desired version using this link:
https://chromium.googlesource.com/chromium/src/+refs
After you got your sources (e.g. the latest for version 62
is: 62.0.3202.101 and it can be found here:
https://chromium.googlesource.com/chromium/src.git/+/62.0.3202.101) you can
build them using your Linux machine. Corresponding guides you can find
here:
https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md

If the way of building sources doesn't work for you well, you still can
find the version you need as a prebuilt snapshot, but I didn't find any
easy way to do this yet. The problem is that there's a special number that
is being used for snapshots that differs from actual version number
(e.g. *`526333`
*stands for `Chromium 65.0.3307.0`).
However, using available API you can try to find version that suits you.
Here's an example for snapshot id `525333` that gives you corresponding Git
commit: https://cr-rev.appspot.com/_ah/api/crrev/v1/redirect/526333
Using this link, you can see that `"redirect_url": "
https://chromium.googlesource.com/chromium/src/+/7e54f884b0c071156d23d8d3f96d1da3b3fac99a
",`
In Chromium sources, version is stored in `chrome/VERSION` file, so, what
you can do to see the version corresponding to the commit we found using
last URL is to open version file like this: `
https://chromium.googlesource.com/chromium/src/+/7e54f884b0c071156d23d8d3f96d1da3b3fac99a/chrome/VERSION`
If you repeat these steps for different snapshot ids in
*Linux_ChromiumOS_FullLinux_ChromiumOS_Full*
(
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_ChromiumOS_Full/)
folder, you can find the version you need.
It's not easy, but still possible.

I hope this will help you. If you find any easier solution or solve your
problem in any other way, please write your findings here, so everyone can
contribute of them.
When I got a bit of time, I will update the code of `node-chromium` to work
properly with the new Linux binaries.

Kind regards,
Dmytro TOLSTYI


On 28 Dec 2017 5:05 pm, "Jean-Marcel Belmont" <notifications@github.com>
wrote:

Hello Dmytro,

First off thanks for this yarn package, it is great. I have a question, how
can I download chromium for linux x64 architecture and specifically version
62? What would be the proper url for it?

Sincerely,

Jean-Marcel Belmont

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dtolstyi/node-chromium/issues/1>, or mute the thread

**Comment by dtolstyi** [comment]
Hi, Jean-Marcel (@jbelmont),

Thank you for your message. I will try to help you with your problem.

As far as I know, there are no separate prebuilt packages for linux x32 and x64 architectures.
In addition, latest build in "Linux" snapshots dates to 2016.
As far as I understood, from now all Linux packages are stored in [**Linux_ChromiumOS_Full**](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_ChromiumOS_Full/) folder.

First, I would recommend you to try to run the latest build of **Chromium** from the folder I've mentioned before. For the moment of writing, here's the link to the latest version:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_ChromiumOS_Full/526333/

If this doesn't work for you, the easiest way to get version 62 is to build it yourself. You can find sources of the desired version using this link: https://chromium.googlesource.com/chromium/src/+refs
After you got your sources (e.g. the latest for version 62 is: 62.0.3202.101 and it can be found here:
https://chromium.googlesource.com/chromium/src.git/+/62.0.3202.101) you can build them using your Linux machine. Corresponding guides you can find here: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md

If the way of building sources doesn't work for you well, you can still find the version you need as a prebuilt snapshot, but I didn't find any easy way to do this yet. The problem is that there's a special number that is being used for snapshots that differs from actual version number (e.g. `526333` stands for `Chromium 65.0.3307.0`).
However, using Chromium API you can try to find version that suits you. Here's an example for snapshot id `525333` that gives you corresponding Git commit: https://cr-rev.appspot.com/_ah/api/crrev/v1/redirect/526333
Using this link, you can see this: `"redirect_url": "https://chromium.googlesource.com/chromium/src/+/7e54f884b0c071156d23d8d3f96d1da3b3fac99a
",`
In Chromium sources, version is stored in `chrome/VERSION` file, so, what you can do to see the version corresponding to the commit we found using last URL is to open version file like this: https://chromium.googlesource.com/chromium/src/+/7e54f884b0c071156d23d8d3f96d1da3b3fac99a/chrome/VERSION
If you repeat these steps for different snapshot ids in [*Linux_ChromiumOS_Fulll*](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_ChromiumOS_Full/) folder, you can find the version you need.
It's not easy but it's possible.

I hope this will help you. If you find any easier solution or solve your problem in any other way, please write your findings here, so everyone can benefit of them.  
When I got a bit of time I will update the code of `node-chromium` to work properly with the new Linux binaries location.

Kind regards,
Dmytro TOLSTYI

**Comment by jbelmont** [comment]
Hello Dmytro,

So I was able to download chromium version 62 by modifying a fork of your repository at [Fork](https://github.com/driq/node-chromium). Here is what I did:

**config.js**

```js
#!/usr/bin/env node

'use strict';

const path = require('path');

module.exports = {
    BIN_OUT_PATH: path.join(__dirname, '../../node_modules/.bin')
};
```

**download-chrome.js**

```js
#!/usr/bin/env node

'use strict';

const fs = require('fs');
const extractZip = require('extract-zip');
const got = require('got');
const tmp = require('tmp');

const config = require('./config');
const utils = require('./utils');

const npmPackage = '62.0.0';
let versionsWithUnknownBranchingPoint = [];

function getOsCdnUrl() {
    let url = 'https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/';

    const platform = process.platform;

    if (platform === 'linux') {
        url += 'Linux';
        if (process.arch === 'x64') {
            url += '_x64';
        }
    } else if (platform === 'win32') {
        url += 'Win';
        if (process.arch === 'x64') {
            url += '_x64';
        }
    } else if (platform === 'darwin') {
        url += 'Mac';
    } else {
        console.log('Unknown platform or architecture found:', process.platform, process.arch);
        throw new Error('Unsupported platform');
    }

    return url;
}

function getCurrentOs() {
    const platform = process.platform;

    if (platform === 'linux') {
        return 'linux';
    }

    if (platform === 'win32') {
        return 'win';
    }

    if (platform === 'darwin') {
        return 'mac';
    }

    console.log('Unknown platform found:', process.platform);
    throw new Error('Unsupported platform');
}

function getExactChromeVersionNumber() {
    return new Promise((resolve, reject) => {
        const url = 'https://omahaproxy.appspot.com/history.json?channel=stable&os=' + getCurrentOs();
        const packageMajorVersion = npmPackage.split('.')[0];

        got(url)
            .then(response => {
                    let versions = JSON.parse(response.body);

                    for (let version of versions) {
                        let versionNumber = version['version'];
                        let buildMajorVersion = versionNumber.split('.')[0];

                        if (buildMajorVersion !== packageMajorVersion) {
                            continue;
                        }

                        if (versionsWithUnknownBranchingPoint.includes(versionNumber)) {
                            continue
                        }

                        resolve(versionNumber);
                    }
                }
            )
            .catch(err => {
                console.log('An error occured while trying to retrieve latest revision number', err);
                reject(err);
            });
    });
}

function getChromiumBranchingPoint(versionNumber) {
    return new Promise((resolve, reject) => {
        const url = 'https://omahaproxy.appspot.com/deps.json?version=' + versionNumber;

        got(url)
            .then(response => {
                let versionDetails = JSON.parse(response.body);
                let branchingPoint = parseInt(versionDetails['chromium_base_position']);

                if (!Number.isInteger(branchingPoint)) {
                    console.log('Could not find branching point for Chrome ' + versionNumber + '. This can happen when the new Chrome version is just branched off. Let\'s try to find the branching point for one version earlier.');
                    versionsWithUnknownBranchingPoint.push(versionNumber);

                    resolve(getExactChromeVersionNumber().then(getChromiumBranchingPoint));
                }

                console.log('Found that Chrome ' + versionNumber + ' was branched off Chromium at point ' + branchingPoint);

                resolve(branchingPoint);
            })
            .catch(err => {
                console.log('Could not get build details for version ' + versionNumber);
                reject(err);
            });

    });
}

function createTempFile() {
    return new Promise((resolve, reject) => {
        tmp.file((error, path) => {
            if (error) {
                console.log('An error occured while trying to create temporary file', error);
                reject(error);
            } else {
                resolve(path);
            }
        });
    });
}

function downloadChromiumRevision(revision) {
    return new Promise((resolve, reject) => {
        createTempFile()
            .then(path => {
                console.log('Downloading Chromium build at branching point ' + revision + ' from Google CDN');
                const url = getOsCdnUrl() + `%2F${revision}%2F` + utils.getOsChromiumFolderName() + '.zip?alt=media';
                got.stream(url)
                    .on('error', () => {
                        console.log('Could not find a Chromium build for branching point ' + revision + '. Trying one point later.');
                        let nextRevision = revision + 1;

                        resolve(downloadChromiumRevision(nextRevision));
                    })
                    .pipe(fs.createWriteStream(path))
                    .on('error', error => {
                        console.log('An error occurred while trying to save Chromium archive to disk', error);
                        reject(error);
                    })
                    .on('finish', () => {
                        resolve(path);
                    });
            });
    });
}

function unzipArchive(archivePath, outputFolder) {
    console.log('Started extracting archive', archivePath);
    return new Promise((resolve, reject) => {
        extractZip(archivePath, {dir: outputFolder}, error => {
            if (error) {
                console.log('An error occurred while trying to extract archive', error);
                reject(error);
            } else {
                console.log('Archive was successfully extracted');
                resolve(true);
            }
        });
    });
}

module.exports = getExactChromeVersionNumber()
    .then(getChromiumBranchingPoint)
    .then(downloadChromiumRevision)
    .then(path => unzipArchive(path, config.BIN_OUT_PATH))
    .catch(err => console.error('An error occurred while trying to setup Chromium. Resolve all issues and restart the process', err));
```

**index.js**

```js
'use strict';

const fs = require('fs');

const utils = require('./utils');

function getBinaryPath() {
    const path = utils.getOsChromiumBinPath();

    if (fs.existsSync(path)) {
        return path;
    }

    return undefined;
}

module.exports = {
    path: getBinaryPath()
};
```

**utils.js**

```js
#!/usr/bin/env node

'use strict';

const path = require('path');

const config = require('./config');

module.exports = {
    getOsChromiumFolderName() {
        const platform = process.platform;

        let archivePlatformPrefix = platform;

        if (platform === 'darwin') {
            archivePlatformPrefix = 'mac';
        }

        return `chrome-${archivePlatformPrefix}`;
    },

    getOsChromiumBinPath() {
        let binPath = path.join(config.BIN_OUT_PATH, this.getOsChromiumFolderName());

        const platform = process.platform;

        if (platform === 'linux') {
            binPath = path.join(binPath, 'chrome');
        } else if (platform === 'win32') {
            binPath = path.join(binPath, 'chrome.exe');
        } else if (platform === 'darwin') {
            binPath = path.join(binPath, 'Chromium.app/Contents/MacOS/Chromium');
        } else {
            console.error('Unsupported platform or architecture found:', process.platform, process.arch);
            throw new Error('Unsupported platform');
        }

        return binPath;
    }
};
```

In the driq fork there is a couple of new functions that he added but essentially I changed the part where he reads in package.json version and put a constant string value of `'62.0.0'` and also changed the bin out directory. 

I just added a step to download chrome using `node download-chrome.js`.

I was thinking it we could use a commandline parameter to specify a chrome version like `CHROME_VERSION="62.0.0" node download-chrome.js` and then it could be read like `process.env.CHROME_VERSION` that way you can specify your specific chromium version that you want. Anyways thanks for getting back to me and I hope this synopsis helps.

**Comment by dtolstyi** [comment]
We can use https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F607962%2Fchrome-linux.zip?alt=media information for older releases

**Comment by maxsinev** [comment]
I have a similar problem but with a [Selenium example](https://github.com/dtolstyi/node-chromium#selenium-webdriver-headless-without-ui-tests) in the README. It looks like current `chromedriver`(76.0.1) is not compatible with version that `node-chromium` loads by default (for now it is 78) and throw an error about incorrect chrome version.

Specifying a chrome version to load would be a great feature.

Thanks!

**Comment by dtolstyi** [comment]
@maxsinev Thank you for you comment Max. I will take a look how complicated it's to implement this feature. Otherwise, if you got some free time to implement this feature I would be really grateful for your PR.

**Comment by ManuelDeLeon** [comment]
@dtolstyi How would the install know which specific version to download? My first thought was to use environment variables but that has issues with multi-tenancy (at least on Windows). What do you think of reading a property from package.json instead?

**Comment by dtolstyi** [comment]
@ManuelDeLeon I like both solutions and env variables seem viable for Windows as well. You can set "session" variables by using `set ...` in `cmd` and it will set variable only for current instance of CMD.
So, you can have global variable as a system default value and specify version you need for a specific installation before running `npm install`.
`package.json` solution I like as well.
It's possible to have both of them as well (there are many systems that work like this). So, first it looks for env variable, then config, e.t.c.

**Comment by ccorcos** [comment]
I made the following package as a fork with fixed versions: https://github.com/ccorcos/chromium-version

You can install a specific version of chrome by installing this package pinned at a specific major version:

```sh
npm install --save chromium-version@77
npm install --save chromium-version@78
npm install --save chromium-version@79
npm install --save chromium-version@80
```

**Comment by dtolstyi** [comment]
Hi @ccorcos. Sounds interesting. Thank you for your work!
Am I right that you need to deploy a new version every time the new version of Chromium is released?

**Comment by ccorcos** [comment]
You are correct. In my case though, any specific version of `chromedriver` only works with a specific version of chrome. This `chromedriver@77` only works with `chromium-version@77`. Your package currently installs Chromium 80 and `chromedriver` hasn't been upgraded to work with 80 yet. Your package will also upgrade at any moment, breaking old integrations with chromedriver... Basically the example in your readme about using chromedriver + selenium doens't currently work.

**Comment by nicholas-johnson** [comment]
This would be a really useful feature. We need this specifically because we need to keep selenium and chrome version numbers in sync.

**Comment by ccorcos** [comment]
@nicholas-johnson you can use my fork in the meantime :)

**Comment by dhAlcojor** [comment]
@ccorcos I like your chromium-version, but... I guess it's not possible to use it with the latest versions? I tried to install chromium-version@81 and got an error. I'm guessing you have to release a new version of chromium-version for each new version of Chromium?

**Comment by ccorcos** [comment]
Ah yes, I haven't released a new version for that.

**Comment by ccorcos** [comment]
I see whats going on now. Thanks for bringing this up @dhAlcojor. I added a comment in the readme about the issue and what needs to be fixed. Sadly, I do not have the time to fix it myself right now but feel free to submit a PR!

**Comment by dhAlcojor** [comment]
Where can I find the matching between Chromium version and revision? As far as I can tell, I'd have to traverse the revision list (https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html), going to the source to check what's the version for each revision.

**Comment by dtolstyi** [comment]
Implemented in PR from @dhAlcojor.
