### ISSUE TITLE
1.1.0 breaks semantic versioning

### ISSUE THREAD

**Issue by weeman1337** [dtolstyi/node-chromium#12]
I have a project that is built on NodeJS 6.  
With 1.1.0 this node version was dropped.

Our dependencies have now been updated from 1.0.2 to 1.1.0 because of semantic versioning (no breaking). But dropping a node version is (in my opinion) breaking.

I didn't find any info about the versioning of this project. Maybe would be good to add info about that.

**Comment by dtolstyi** [comment]
Hi Michael @weeman1337,

Sorry to hear that the new release has broken your builds.
You are absolutely right that this release is not back compatible for NodeJS vs.6 because I've rewrote the logic using `async/await` syntax.

Honestly, I didn't think that there are still any user of NodeJS 6.x as far as it's support is going to be stopped in a few months.

Sorry for inconveniences. I think I will release 2 new versions:
- **1.2.1** without `async` functions
- **2.0.0** with `async` functions

Like this, we will be in line wiht `semver` rules.

Thank you for pointing this out.

**Comment by dtolstyi** [comment]
Version **1.1.1** is up and should be back-compatible with **1.0.1**.

**Comment by weeman1337** [comment]
@dtolstyi thanks - that was fast!

**Comment by dtolstyi** [comment]
You are welcome, Michael @weeman1337. I hope it will work fine )
